"""Initial schema

Revision ID: 8a988a30376b
Revises: 
Create Date: 2025-12-27 17:48:16.906806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a988a30376b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique session identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Session creation timestamp'),
    sa.Column('last_active_at', sa.DateTime(), nullable=False, comment='Last activity timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique conversation identifier'),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='Foreign key to user_sessions'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='Auto-generated conversation title'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Conversation creation timestamp'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique message identifier'),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Foreign key to conversations'),
    sa.Column('role', sa.String(length=20), nullable=False, comment="Message role: 'user' or 'assistant'"),
    sa.Column('content', sa.Text(), nullable=False, comment='Message text content'),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Citations for assistant responses (JSON array of {chapter, section, page})'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Message timestamp'),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='check_message_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
