"""add_is_deleted_to_conversations

Revision ID: a5b38b6b02e4
Revises: c792fa3be29f
Create Date: 2025-12-28 04:09:54.561526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5b38b6b02e4'
down_revision: Union[str, None] = 'c792fa3be29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rate_limits_session_id', table_name='rate_limits')
    op.drop_index('ix_rate_limits_window_start', table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index('ix_feedback_message_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_user_profiles_session_id', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.add_column('conversations', sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_deleted')
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('knowledge_level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='knowledgelevel'), autoincrement=False, nullable=False),
    sa.Column('visited_chapters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('total_questions', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], name='user_profiles_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_profiles_pkey')
    )
    op.create_index('ix_user_profiles_session_id', 'user_profiles', ['session_id'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='feedback_message_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='feedback_pkey')
    )
    op.create_index('ix_feedback_message_id', 'feedback', ['message_id'], unique=False)
    op.create_table('rate_limits',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], name='rate_limits_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='rate_limits_pkey'),
    sa.UniqueConstraint('session_id', 'window_start', name='uq_session_window')
    )
    op.create_index('ix_rate_limits_window_start', 'rate_limits', ['window_start'], unique=False)
    op.create_index('ix_rate_limits_session_id', 'rate_limits', ['session_id'], unique=False)
    # ### end Alembic commands ###
