"""Add user profiles for personalization

Revision ID: 70118de13ac5
Revises: 8a988a30376b
Create Date: 2025-12-27 22:16:56.260941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '70118de13ac5'
down_revision: Union[str, None] = '8a988a30376b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_profiles',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('knowledge_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='knowledgelevel'), nullable=False),
        sa.Column('visited_chapters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('total_questions', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_session_id'), 'user_profiles', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_session_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.execute('DROP TYPE knowledgelevel')
    # ### end Alembic commands ###
